type: deploy.robot.so101.So101FollowerWithCamera
name: so101followerwithcamera
args:
  com: /dev/ttyACM1
  robot_id: so101_follower
  camera_configs:
    front_camera:
      index_or_path: /dev/video2
      width: 640
      height: 480
      fps: 30
  use_lock: true
