type: deploy.action_manager.truncated.TruncatedManager
name: truncated_conservative
args:
  module_path: deploy.action_manager.truncated
  class_name: TruncatedManager
  start_ratio: 0.1
  end_ratio: 0.2
  older_coef: 1.0
