type: policy.act
name: act
args:
  backbone: resnet18
  dilation: false
  position_embedding: sine
  camera_names:
  - primary
  enc_layers: 4
  dec_layers: 7
  dim_feedforward: 3200
  hidden_dim: 512
  dropout: 0.1
  nheads: 8
  chunk_size: 100
  pre_norm: false
  masks: false
  lr_backbone: 1.0e-05
  kl_weight: 10
  state_dim: 14
  action_dim: 14
  history_len: 1
  prediction_len: 100
  num_queries: 100
