type: policy.diffusion_policy
name: diffusion_policy
args:
  action_dim: 7
  state_dim: 7
  chunk_size: 64
  n_action_steps: 64
  n_obs_steps: 1
  num_inference_steps: 10
  noise_scheduler: ddpm
  noise_scheduler_kwargs: {}
  camera_names:
  - primary
  obs_encoder: resnet18
  obs_encoder_kwargs: {}
  action_encoder: temporal
  action_encoder_kwargs: {}
  action_decoder: temporal
  action_decoder_kwargs: {}
  use_pretrained_weights: true
  pretrained_model_path: null
