type: policy.diffusion_policy
name: diffusion_policy
args:
  action_dim: 28
  state_dim: 39
  horizon: 100
  n_action_steps: 100
  n_obs_steps: 1
  num_inference_steps: 10
  camera_names: []
  noise_scheduler: ddpm
  noise_scheduler_kwargs: {}
  obs_encoder: resnet18
  obs_encoder_kwargs: {}
  action_encoder: temporal
  action_encoder_kwargs: {}
  action_decoder: temporal
  action_decoder_kwargs: {}
  use_pretrained_weights: true
  pretrained_model_path: null
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
