type: policy.fm
name: flow_matching
args:
  state_dim: 22
  action_dim: 7
  chunk_size: 1
  time_dim: 64
  hidden_dim: 256
  num_layers: 3
  learning_rate: 0.0001
  num_sampling_steps: 100
  use_ode_solver: true
  ode_atol: 1.0e-05
  ode_rtol: 1.0e-05
