type: policy.fm
name: flow_matching
args:
  state_dim: 57
  action_dim: 14
  chunk_size: 1
  time_dim: 64
  hidden_dim: 256
  num_layers: 3
  learning_rate: 0.0001
  num_sampling_steps: 100
  use_ode_solver: true
  ode_atol: 1.0e-05
  ode_rtol: 1.0e-05
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
