type: policy.mlp
name: mlp
args:
  state_dim: 28
  action_dim: 28
  num_layers: 3
  hidden_dim: 256
  activation: relu
  dropout: 0.1
  use_camera: false
  image_dim: null
  learning_rate: 1e-3
  chunk_size: 1
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
config_class: MLPPolicyConfig
model_class: MLPPolicy
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: null
