type: policy.mlp
name: mlp_small
args:
  state_dim: 14
  action_dim: 14
  num_layers: 2
  hidden_dim: 128
  activation: tanh
  dropout: 0.0
  use_camera: false
  image_dim: null
  learning_rate: 2e-3
  chunk_size: 1
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
config_class: MLPPolicyConfig
model_class: MLPPolicy
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: null
