type: policy.mlp
name: mlp_camera
args:
  state_dim: 14
  action_dim: 14
  num_layers: 4
  hidden_dim: 512
  activation: relu
  dropout: 0.2
  use_camera: true
  image_dim: null
  chunk_size: 16
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
config_class: MLPPolicyConfig
model_class: MLPPolicy
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: null
