type: policy.mlp.MLPPolicy
name: mlp_lowdim
config_class: MLPPolicyConfig
model_class: MLPPolicy
data_processor: get_data_processor
data_collator: null
trainer_class: Trainer
args:
  # Model architecture parameters
  backbone: null
