type: policy.openpi
name: openpi
args:
  pytorch_training_precision: bfloat16
  action_dim: 7
  state_dim: 8
  max_action_dim: 32
  chunk_size: 16
  max_token_len: 48
  paligemma_variant: gemma_2b
  action_expert_variant: gemma_300m
  pi05: false
  discrete_state_input: false
  pytorch_weight_path: /inspire/hdd/project/robot-action/public/models/openpi/pi0_base_torch
  lora_module: []
trainer_class: Trainer
