name: openpi
module_path: policy.openpi
pretrained_config:
  model_name_or_path: "facebook/opt-125m"
  is_pretrained: false
model_args:
  # Model architecture parameters
  pytorch_training_precision: bfloat16
  action_dim: 7
  max_action_dim: 32
  chunk_size: 50
  max_token_len: 48
  paligemma_variant: gemma_2b
  action_expert_variant: gemma_300m
  pi05: False
  # Task parameters (will be overridden by args if provided)
  state_dim: 8
  discrete_state_input: False
  pytorch_weight_path: /inspire/hdd/project/robot-action/public/models/openpi/pi0_base_torch
action_normalize: "minmax"
state_normalize: "minmax"
trainer_class: Trainer