type: policy.openpi
name: openpi
args:
  pytorch_training_precision: bfloat16
  action_dim: 14
  max_action_dim: 32
  chunk_size: 50
  max_token_len: 48
  paligemma_variant: gemma_2b
  action_expert_variant: gemma_300m
  pi05: false
  state_dim: 14
  discrete_state_input: false
  pytorch_weight_path: /root/.cache/openpi/openpi-assets/checkpoints/pi0_base_pytorch
pretrained_config:
  model_name_or_path: facebook/opt-125m
  is_pretrained: false
trainer_class: Trainer
