type: policy.qwen25dp
name: qwen25dp
args:
  vlm_model_name_or_path: /inspire/hdd/project/robot-action/public/models/models--Qwen--Qwen2.5-VL-3B-Instruct/snapshots/66285546d2b821cf421d4f5eb2576359d3770cd3
  policy_action_dim: 7
  policy_state_dim: 8
  policy_prediction_horizon: 100
  lora_enable: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  lora_bias: none
  lora_module: vit,llm,merger
  bits: 16
  bf16: true
  fp16: false
  gradient_checkpointing: true
  freeze_backbone: false
  lora_lr: 1e-4
config_class: QwenVLPolicyConfig
model_class: QwenVLForPolicy
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: Trainer
