type: policy.smolvla
name: smolvla
args:
  model_type: smolvla_policy
  n_obs_steps: 1
  chunk_size: 50
  n_action_steps: 50
  action_dim: 4
  state_dim: 4
  max_state_dim: 32
  max_action_dim: 32
  resize_imgs_with_padding:
  - 512
  - 512
  empty_cameras: 0
  adapt_to_pi_aloha: false
  use_delta_joint_actions_aloha: false
  tokenizer_max_length: 48
  num_steps: 10
  use_cache: true
  freeze_vision_encoder: true
  train_expert_only: false
  train_state_proj: true
  vlm_model_name: HuggingFaceTB/SmolVLM2-500M-Video-Instruct
  load_vlm_weights: true
  add_image_special_tokens: false
  attention_mode: cross_attn
  prefix_length: -1
  pad_language_to: longest
  num_expert_layers: -1
  num_vlm_layers: 16
  self_attn_every_n_layers: 2
  expert_width_multiplier: 0.75
  min_period: 0.004
  max_period: 4.0
  camera_names:
  - primary
  history_len: 1
  prediction_len: 50
pretrained_config:
  model_name_or_path: null
  is_pretrained: false
config_class: SmolVLAPolicyConfig
model_class: SmolVLAPolicy
data_processor: get_data_processor
data_collator: get_data_collator
trainer_class: Trainer
