datasets:
- type: data_utils.datasets.rlds_wrapper.WrappedRLDSDataset
  name: berkeley_autolab_ur5
  args:
    dataset_dir: /inspire/hdd/global_public/public_datas/Robotics_Related/Open-X-Embodiment/openx/
    data_mix: berkeley_autolab_ur5
    chunk_size: 16
    image_size:
    - 256
    - 256
meta:
  action_dim: 7
  state_dim: 8
  action_normalize: zscore
  state_normalize: zscore
