datasets:
- type: data_utils.datasets.rlds_wrapper.WrappedRLDSDataset
  name: bridge_data_v2
  args:
    dataset_dir: /inspire/hdd/project/robot-action/wangzheng-240308120196/data/bridge_data_v2
    data_mix: bridge_dataset
    chunk_size: 1
    image_size:
    - 256
    - 256
meta:
  action_dim: 7
  state_dim: 7
  action_normalize: zscore
  state_normalize: zscore
