datasets:
- type: data_utils.datasets.D4RLDataset
  name: d4rl_relocate_cloned
  args:
    dataset_path_list:
    - D4RL/relocate/cloned-v2
    chunk_size: 1
    ctrl_space: joint
    ctrl_type: abs
meta:
  action_dim: 30
  state_dim: 39
  action_normalize: identity
  state_normalize: identity
