datasets:
- type: data_utils.datasets.D4RLDataset
  name: d4rl_door_human
  args:
    dataset_path_list:
    - D4RL/door/human-v2
    chunk_size: 1
    ctrl_space: joint
    ctrl_type: abs
meta:
  action_dim: 28
  state_dim: 39
  action_normalize: identity
  state_normalize: identity
