datasets:
- type: data_utils.datasets.D4RLDataset
  name: d4rl_hammer_cloned
  args:
    dataset_path_list:
    - D4RL/hammer/cloned-v2
    chunk_size: 1
    ctrl_space: joint
    ctrl_type: abs
meta:
  action_dim: 26
  state_dim: 46
  action_normalize: identity
  state_normalize: identity
