datasets:
  - name: "fractal20220817_data"
    class: "data_utils.datasets.rlds_wrapper.WrappedRLDSDataset"
    args:
      dataset_dir: '/inspire/hdd/global_public/public_datas/Robotics_Related/Open-X-Embodiment/openx/'
      data_mix: "fractal20220817_data"
      chunk_size: 1
      image_size: [256, 256]

# Task-specific parameters that will override policy configs
action_dim: 7
state_dim: 8
action_normalize: "zscore"
state_normalize: "zscore"
episode_len: 400
