datasets:
- type: data_utils.datasets.AlohaSimDataset
  name: insertion_top
  args:
    dataset_path_list:
    - /inspire/hdd/project/robot-action/wangzheng-240308120196/act-plus-plus-main/data/sim_insertion_scripted
    camera_names:
    - primary
    chunk_size: 50
    ctrl_space: joint
    ctrl_type: abs
meta:
  action_dim: 14
  state_dim: 14
  image_size:
  - 640
  - 480
  action_normalize: zscore
  state_normalize: zscore
