datasets:
- type: data_utils.datasets.KochDataset
  name: koch_pick_red_cap
  args:
    dataset_path_list:
    - /home/wwzzz/Code/IL-Studio/data/pick_red_cap_into_cup
    camera_names:
    - primary
    chunk_size: 32
    ctrl_space: joint
    ctrl_type: abs
meta:
  action_dim: 6
  state_dim: 6
  image_size:
  - 640
  - 480
  action_normalize: zscore
  state_normalize: zscore
