datasets:
- type: data_utils.datasets.WrappedLerobotDataset
  name: lerobot_aloha
  args:
    dataset_path_list:
    - lerobot/aloha_mobile_cabinet
    chunk_size: 64
    ctrl_space: joint
    ctrl_type: abs
meta:
  action_dim: 14
  state_dim: 14
  image_size:
  - 640
  - 480
  action_normalize: zscore
  state_normalize: zscore
