# 新的灵活数据集配置格式
datasets:
  - name: "lerobot_bridge_v2"
    class: "WrappedLerobotDataset"
    args:
      dataset_path_list: [BrunoM42/fractal20220817_data_lerobot]
      chunk_size: 1
      ctrl_space: 'ee'
      ctrl_type: 'abs'

# Task-specific parameters
action_dim: 7
state_dim: 8
image_size: [256, 256]
action_normalize: "zscore"
state_normalize: "zscore"





