datasets:
- type: data_utils.datasets.libero_lerobot.LerobotLIBERO
  name: lerobot_libero_from_openpi
  args:
    dataset_path_list:
    - HuggingFaceVLA/libero
    chunk_size: 50
    ctrl_space: ee
    ctrl_type: delta
meta:
  action_dim: 7
  state_dim: 8
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
