datasets:
  - name: "lerobot_metaworld"
    class: "WrappedLerobotDataset"
    args:
      dataset_path_list: [lerobot/metaworld_mt50]
      root: "/inspire/hdd/project/robot-action/public/data/lerobot/metaworld_mt50"
      chunk_size: 64
      ctrl_space: 'ee'
      ctrl_type: 'abs'
      tolerance_s: 10.0
      action_norm_mask: [-1]

# Task-specific parameters
action_dim: 4
state_dim: 4
image_size: [512, 512]
action_normalize: "zscore"
state_normalize: "zscore"

