# 新的灵活数据集配置格式
datasets:
  - name: "lerobot_libero_from_openpi"
    class: "data_utils.datasets.libero_lerobot.LerobotLIBERO"
    args:
      dataset_path_list: [HuggingFaceVLA/libero]
      # root: /inspire/hdd/project/robot-action/public/LIBERO2
      chunk_size: 1
      ctrl_space: 'ee'
      ctrl_type: 'delta'
      camera_names: "observation.images.image"

# Task-specific parameters
action_dim: 7
state_dim: 8
image_size: [256, 256]
action_normalize: "zscore"
state_normalize: "zscore"

