datasets:
- type: data_utils.datasets.WrappedLerobotDataset
  name: lerobot_bridge_v2
  args:
    dataset_path_list:
    - ZibinDong/bridgedatav2_train
    chunk_size: 64
    ctrl_space: ee
    ctrl_type: abs
meta:
  action_dim: 4
  state_dim: 4
  image_size:
  - 256
  - 256
  action_normalize: zscore
  state_normalize: zscore
