datasets:
  - name: "libero_obj_rlds"
    class: "data_utils.datasets.rlds_wrapper.WrappedRLDSDataset"
    args:
      dataset_dir: '/inspire/hdd/project/robot-action/public/data/libero/openvla'
      data_mix: "libero_object_no_noops"
      chunk_size: 1
      image_size: [256, 256]
    action_norm_mask: [-1]


# Task-specific parameters that will override policy configs
action_dim: 7
state_dim: 8
action_normalize: "zscore"
state_normalize: "zscore"
episode_len: 400
