datasets:
- type: data_utils.datasets.libero_h5.LiberoHDF5
  name: libero_object
  args:
    root: /inspire/hdd/project/robot-action/public/data/libero/
    split: object
    camera_names:
    - image_primary
    chunk_size: 16
    image_size:
    - 256
    - 256
    preload_data: true
meta:
  action_dim: 7
  state_dim: 8
  action_normalize: zscore
  state_normalize: zscore
