datasets:
  - name: "lerobot_metaworld"
    class: "WrappedLerobotDataset"
    args:
      dataset_path_list: [wentacc/lerobot_metaworld_reach_v3]
      chunk_size: 50
      ctrl_space: 'ee'
      ctrl_type: 'abs'
      tolerance_s: 10.0
      # action_norm_mask: [-1]

# Task-specific parameters
action_dim: 4
state_dim: 4
image_size: [480, 480]
action_normalize: "zscore"
state_normalize: "zscore"

