# 新的灵活数据集配置格式
datasets:
  - name: "robomimic_can_mh_lowdim_only"
    class: "RobomimicDataset"
    args:
      dataset_path_list: ['/inspire/hdd/project/robot-action/public/data/robomimic/can/mh']
      ctrl_space: 'ee'
      ctrl_type: 'delta'
      use_wrist_img: false
      chunk_size: 1
      use_img: false
      use_low_dim: true
    action_norm_mask: [-1]

episode_len: 400
action_dim: 7
state_dim: 22
action_normalize: "identity"
state_normalize: "identity"