# 新的灵活数据集配置格式
datasets:
  - name: "robomimic_square_ph_lowdim_only"
    class: "RobomimicDataset"
    args:
      dataset_path_list: ['/inspire/hdd/project/robot-action/public/data/robomimic/square/ph']
      ctrl_space: 'ee'
      ctrl_type: 'delta'
      use_wrist_img: false
      use_img: false
      use_low_dim: true
    action_norm_mask: [-1]

episode_len: 400
action_dim: 7
state_dim: 22
action_normalize: "zscore"
state_normalize: "zscore"