datasets:
- type: data_utils.datasets.RobomimicDataset
  name: robomimic_square_ph_lowdim_only
  args:
    dataset_path_list:
    - /inspire/hdd/project/robot-action/public/data/robomimic/square/ph
    ctrl_space: ee
    ctrl_type: delta
    use_wrist_img: false
    chunk_size: 1
    use_img: false
    use_low_dim: true
meta:
  action_dim: 7
  state_dim: 22
  action_normalize: identity
  state_normalize: identity
