datasets:
- type: data_utils.datasets.RobomimicDataset
  name: robomimic_square_ph
  args:
    dataset_path_list:
    - /inspire/hdd/project/robot-action/public/data/robomimic/square/ph
    camera_names:
    - primary
    ctrl_space: ee
    ctrl_type: delta
    preload_data: true
meta:
  action_dim: 7
  state_dim: 7
  action_normalize: zscore
  state_normalize: zscore
