datasets:
- type: data_utils.datasets.RobomimicDataset
  name: robomimic_square_ph
  args:
    dataset_path_list:
    - /inspire/hdd/project/robot-action/public/data/robomimic/square/ph
    camera_names:
    - primary
    chunk_size: 50
    ctrl_space: ee
    ctrl_type: delta
- type: data_utils.datasets.RobomimicDataset
  name: robomimic_square_mh
  args:
    dataset_path_list:
    - /inspire/hdd/project/robot-action/public/data/robomimic/square/mh
    camera_names:
    - primary
    chunk_size: 50
    ctrl_space: ee
    ctrl_type: delta
meta:
  action_dim: 7
  state_dim: 7
  image_size:
  - 256
  - 256
  action_normalize: minmax
  state_normalize: minmax
