datasets:
- type: data_utils.datasets.RobomimicDataset
  name: robomimic_transport_ph_lowdim_only
  args:
    dataset_path_list:
    - /inspire/hdd/project/robot-action/public/data/robomimic/transport/ph
    - /inspire/hdd/project/robot-action/public/data/robomimic/transport/mh
    ctrl_space: ee
    ctrl_type: delta
    use_wrist_img: false
    chunk_size: 1
    use_img: false
    use_low_dim: true
meta:
  action_dim: 14
  state_dim: 57
  action_normalize: identity
  state_normalize: identity
