datasets:
- type: data_utils.datasets.vlaos.VLAOSDataset
  name: libero_object
  args:
    dataset_dir: /inspire/hdd/project/robot-action/public/data/VLA-OS-Dataset/libero
    data_mix: libero_object
meta:
  action_dim: 8
  state_dim: 8
  action_normalize: zscore
  state_normalize: zscore
