type: deploy.teleoperator.tk_slider.SliderTeleop
name: slider
args:
  shm_name: ilstd_teleop_controller
  action_dim: 9
  action_dtype: float64
  freq: 100.0
  slider_ranges:
  - - -2.0
    - 2.0
  - - -2.0
    - 2.0
  - - -2.0
    - 2.0
  - - -2.0
    - 2.0
  - - -2.0
    - 2.0
  - - -2.0
    - 2.0
  - - -2.0
    - 2.0
  - - 0.0
    - 0.04
  - - 0.0
    - 0.04
