type: gymnasium_robotics
name: AdroitHandDoor-v1
args:
  task: AdroitHandDoor-v1
  max_timesteps: 400
  ctrl_space: joint
  ctrl_type: abs
  use_camera: true
  camera_ids:
  - 0
  image_size:
  - 640
  - 480
