- type: benchmark.libero.LiberoEnv
  name: libero_object_0
  args:
    task: libero_object_0
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0

- type: benchmark.libero.LiberoEnv
  name: libero_object_1
  args:
    task: libero_object_1
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0

- type: benchmark.libero.LiberoEnv
  name: libero_object_2
  args:
    task: libero_object_2
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0

- type: benchmark.libero.LiberoEnv
  name: libero_object_3
  args:
    task: libero_object_3
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0
    
- type: benchmark.libero.LiberoEnv
  name: libero_object_4
  args:
    task: libero_object_4
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0

- type: benchmark.libero.LiberoEnv
  name: libero_object_5
  args:
    task: libero_object_5
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0

- type: benchmark.libero.LiberoEnv
  name: libero_object_6
  args:
    task: libero_object_6
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0

- type: benchmark.libero.LiberoEnv
  name: libero_object_7
  args:
    task: libero_object_7
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0

- type: benchmark.libero.LiberoEnv
  name: libero_object_8
  args:
    task: libero_object_8
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0
    
- type: benchmark.libero.LiberoEnv
  name: libero_object_9
  args:
    task: libero_object_9
    max_timesteps: 400
    ctrl_space: ee
    image_size:
    - 256
    - 256
    camera_ids:
    - 0