- type: benchmark.aloha.AlohaSimEnv
  name: sim_transfer_cube_scripted
  args:
    task: sim_transfer_cube_scripted
    max_timesteps: 400
    ctrl_space: joint
    ctrl_type: abs
    camera_ids:
    - 0
    image_size:
    - 640
    - 480
- type: benchmark.aloha.AlohaSimEnv
  name: sim_insertion_scripted
  args:
    task: sim_insertion_scripted
    max_timesteps: 400
    ctrl_space: joint
    ctrl_type: abs
    camera_ids:
    - 0
    image_size:
    - 640
    - 480
