type: benchmark.metaworld.MetaworldEnv
name: reach-v3
args:
  task: reach-v3
  max_timesteps: 128
  ctrl_space: ee
  ctrl_type: abs
  use_camera: true
  camera_name: corner4
  image_size:
  - 480
  - 480
