- type: benchmark.metaworld.MetaworldEnv
  name: button-press-v3
  args:
    task: button-press-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: button-press-topdown-v3
  args:
    task: button-press-topdown-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: button-press-topdown-wall-v3
  args:
    task: button-press-topdown-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: button-press-wall-v3
  args:
    task: button-press-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: coffee-button-v3
  args:
    task: coffee-button-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: dial-turn-v3
  args:
    task: dial-turn-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: door-close-v3
  args:
    task: door-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: door-lock-v3
  args:
    task: door-lock-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: door-open-v3
  args:
    task: door-open-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: door-unlock-v3
  args:
    task: door-unlock-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: drawer-close-v3
  args:
    task: drawer-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: drawer-open-v3
  args:
    task: drawer-open-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: faucet-close-v3
  args:
    task: faucet-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: faucet-open-v3
  args:
    task: faucet-open-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: handle-press-v3
  args:
    task: handle-press-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: handle-press-side-v3
  args:
    task: handle-press-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: handle-pull-v3
  args:
    task: handle-pull-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: handle-pull-side-v3
  args:
    task: handle-pull-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: lever-pull-v3
  args:
    task: lever-pull-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: plate-slide-v3
  args:
    task: plate-slide-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: plate-slide-back-v3
  args:
    task: plate-slide-back-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: plate-slide-back-side-v3
  args:
    task: plate-slide-back-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: plate-slide-side-v3
  args:
    task: plate-slide-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: reach-v3
  args:
    task: reach-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: reach-wall-v3
  args:
    task: reach-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: window-close-v3
  args:
    task: window-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: window-open-v3
  args:
    task: window-open-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: peg-unplug-side-v3
  args:
    task: peg-unplug-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480
- type: benchmark.metaworld.MetaworldEnv
  name: basketball-v3
  args:
    task: basketball-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: bin-picking-v3
  args:
    task: bin-picking-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: box-close-v3
  args:
    task: box-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: coffee-pull-v3
  args:
    task: coffee-pull-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: coffee-push-v3
  args:
    task: coffee-push-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: hammer-v3
  args:
    task: hammer-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: peg-insert-side-v3
  args:
    task: peg-insert-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: push-wall-v3
  args:
    task: push-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: soccer-v3
  args:
    task: soccer-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: sweep-v3
  args:
    task: sweep-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: sweep-into-v3
  args:
    task: sweep-into-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: assembly-v3
  args:
    task: assembly-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: hand-insert-v3
  args:
    task: hand-insert-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: pick-out-of-hole-v3
  args:
    task: pick-out-of-hole-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: pick-place-v3
  args:
    task: pick-place-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: push-v3
  args:
    task: push-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: push-back-v3
  args:
    task: push-back-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: shelf-place-v3
  args:
    task: shelf-place-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: disassemble-v3
  args:
    task: disassemble-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: stick-pull-v3
  args:
    task: stick-pull-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: stick-push-v3
  args:
    task: stick-push-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: pick-place-wall-v3
  args:
    task: pick-place-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

