- type: benchmark.metaworld.MetaworldEnv
  name: button-press-v3
  args:
    task: button-press-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: button-press-topdown-v3
  args:
    task: button-press-topdown-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: button-press-topdown-wall-v3
  args:
    task: button-press-topdown-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: button-press-wall-v3
  args:
    task: button-press-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: coffee-button-v3
  args:
    task: coffee-button-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: dial-turn-v3
  args:
    task: dial-turn-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: door-close-v3
  args:
    task: door-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: door-lock-v3
  args:
    task: door-lock-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: door-open-v3
  args:
    task: door-open-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: door-unlock-v3
  args:
    task: door-unlock-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: drawer-close-v3
  args:
    task: drawer-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: drawer-open-v3
  args:
    task: drawer-open-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: faucet-close-v3
  args:
    task: faucet-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: faucet-open-v3
  args:
    task: faucet-open-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: handle-press-v3
  args:
    task: handle-press-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: handle-press-side-v3
  args:
    task: handle-press-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: handle-pull-v3
  args:
    task: handle-pull-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: handle-pull-side-v3
  args:
    task: handle-pull-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: lever-pull-v3
  args:
    task: lever-pull-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: plate-slide-v3
  args:
    task: plate-slide-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: plate-slide-back-v3
  args:
    task: plate-slide-back-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: plate-slide-back-side-v3
  args:
    task: plate-slide-back-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: plate-slide-side-v3
  args:
    task: plate-slide-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: reach-v3
  args:
    task: reach-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: reach-wall-v3
  args:
    task: reach-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: window-close-v3
  args:
    task: window-close-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: window-open-v3
  args:
    task: window-open-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: peg-unplug-side-v3
  args:
    task: peg-unplug-side-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480
