- type: benchmark.metaworld.MetaworldEnv
  name: assembly-v3
  args:
    task: assembly-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: hand-insert-v3
  args:
    task: hand-insert-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: pick-out-of-hole-v3
  args:
    task: pick-out-of-hole-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: pick-place-v3
  args:
    task: pick-place-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: push-v3
  args:
    task: push-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: push-back-v3
  args:
    task: push-back-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

