- type: benchmark.metaworld.MetaworldEnv
  name: shelf-place-v3
  args:
    task: shelf-place-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: disassemble-v3
  args:
    task: disassemble-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: stick-pull-v3
  args:
    task: stick-pull-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: stick-push-v3
  args:
    task: stick-push-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

- type: benchmark.metaworld.MetaworldEnv
  name: pick-place-wall-v3
  args:
    task: pick-place-wall-v3
    max_timesteps: 128
    ctrl_space: ee
    ctrl_type: abs
    use_camera: true
    camera_name: corner4
    image_size:
    - 480
    - 480

