type: benchmark.panda_gym.PandaGymEnv
name: PandaReach
args:
  task: PandaReach
  max_timesteps: 50
  ctrl_space: ee
  ctrl_type: abs
  use_camera: true
  render_mode: rgb_array
  renderer: Tiny
  use_dense_reward: false
