type: benchmark.panda_gym.PandaGymEnv
name: PandaPickAndPlace
args:
  task: PandaPickAndPlace
  max_timesteps: 100
  ctrl_space: ee
  ctrl_type: abs
  use_camera: true
  render_mode: rgb_array
  renderer: OpenGL
  use_dense_reward: true
